# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

parallelMatrixSquareDist <- function(x, i) {
    .Call('_scluster_parallelMatrixSquareDist', PACKAGE = 'scluster', x, i)
}

parallelMatrixCidrDist <- function(x, truth, i, threshold) {
    .Call('_scluster_parallelMatrixCidrDist', PACKAGE = 'scluster', x, truth, i, threshold)
}

vectorMatrixProduct <- function(AA, BB) {
    .Call('_scluster_vectorMatrixProduct', PACKAGE = 'scluster', AA, BB)
}

